{{- if and .Values.secrets.create (not .Values.secrets.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}




